#!/usr/bin/env python3

"""
Created on 4 Jan 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_api

DESCRIPTION
Manages JSON Web Token (JWT) timeout

SYNOPSIS
mrcs_token_timeout [-h] [-i INDENT] [-v] [--version] [-s HOURS MINUTES]

EXAMPLES
mrcs_token_timeout -s 2 0

FILES
~/MRCS/conf/token_timeout.json
"""

import logging
import sys

from mrcs_api.cli.args.token_timeout_args import TokenTimeoutArgs
from mrcs_api.security.token_timeout import TokenTimeout
from mrcs_core.data.json import JSONify
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = TokenTimeoutArgs('manages JSON Web Token (JWT) timeout')

    Logging.config('mrcs_token_timeout', level=logging.INFO)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    # ----------------------------------------------------------------------------------------------------------------

    timeout = TokenTimeout.load(Host)

    try:
        if args.set:
            timeout = TokenTimeout(args.hours, args.minutes)
            timeout.save(Host)

        print(JSONify.dumps(timeout, indent=args.indent))

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
