#!/usr/bin/env python3

"""
Created on 30 Nov 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_api

DESCRIPTION
A launcher for the Uvicorn ASGI web server

SYNOPSIS
mrcs_uvicorn [-h] [-i INDENT] [-v] [--version] [-t] [-p PORT] [-r]

EXAMPLES
mrcs_uvicorn -t -v -r
"""

import sys

import uvicorn

from mrcs_api.cli.args.uvicorn_args import UvicornArgs
from mrcs_control.sys.environment import Environment
from mrcs_core.sys.env_paths import EnvPaths
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = UvicornArgs('a launcher for the Uvicorn ASGI web server')

    Logging.config('mrcs_uvicorn', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')
    logger.info(f'mode: {args.mode.value}')

    Environment.set(args.mode)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        if args.reload:
            watched = EnvPaths.mrcs()
            logger.info(f'watched: {watched}')
            uvicorn.run('mrcs_api.app.main:app', host='0.0.0.0', port=args.port, reload=True, reload_dirs=[watched])
        else:
            uvicorn.run('mrcs_api.app.main:app', host='0.0.0.0', port=args.port)


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
